"""empty message

Revision ID: 51bc06c81468
Revises: 5e112f6c8510
Create Date: 2020-07-25 23:57:39.550835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bc06c81468'
down_revision = '5e112f6c8510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'sistema_o')
    op.drop_column('usuario', 'almacenamiento')
    op.drop_column('usuario', 'procesador')
    op.drop_column('usuario', 'direct_x')
    op.drop_column('usuario', 'gusto')
    op.drop_column('usuario', 'fecha')
    op.drop_column('usuario', 'grafica')
    op.drop_column('usuario', 'ram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('ram', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('grafica', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('fecha', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usuario', sa.Column('gusto', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('direct_x', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('procesador', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('almacenamiento', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('sistema_o', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
