"""empty message

Revision ID: 554ae8413672
Revises: 
Create Date: 2020-07-26 14:31:14.547065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554ae8413672'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('razon_social', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('fecha', sa.String(), nullable=False),
    sa.Column('sistema_o', sa.String(), nullable=True),
    sa.Column('procesador', sa.String(), nullable=True),
    sa.Column('almacenamiento', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('grafica', sa.String(), nullable=True),
    sa.Column('direct_x', sa.String(), nullable=True),
    sa.Column('gusto', sa.String(), nullable=True),
    sa.Column('confirmation', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('empresa')
    # ### end Alembic commands ###
