"""empty message

Revision ID: 98fa737b87d2
Revises: 554ae8413672
Create Date: 2020-07-26 16:09:36.377473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fa737b87d2'
down_revision = '554ae8413672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'age',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'confirmation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'confirmation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'age',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
